spring.datasource:
  url: "jdbc:h2:file:${HOME}/.memos/sync"
  username: sync
  password: sync
  driver-class-name: "org.h2.Driver"
spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:config/master.yaml
  jackson:
    serialization:
      write-dates-as-timestamps: false